config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get "welcome" => "welcome#index"

  resources :abnormals do
    collection do
      get :download_excel
      post :import
      post :check_reason
      get :word_cloud
      get :excel_file_status
    end
    member do
      post :update_envelop
    end
  end
  resources :imports do
    member do
      get :download_csv
    end
  end
  resources :form_options do
    member do
      post :delete_item
    end
  end
end

app/models/form_option.rb
class FormOption < ApplicationRecord
end

app/controllers/form_options_controller.rb
class FormOptionsController < ApplicationController
  def index
    @form_options = FormOption.all
    @form_option = FormOption.new
  end

  def create
    @form_option = FormOption.new(form_option_params)
    if @form_option.save
      redirect_to :back, notice: "新增成功"
    else
      redirect_to :back, alert: "新增失败！，检查：第一个输入框为空或者内容已存在！"
    end
  end

  def update
    @form_option = FormOption.find(params[:id])
    if @form_option.content.split('&').include?(params[:content])
      redirect_to :back, alert: "您添加的【#{params[:content]}】已存在，不要重复增加哦！"
    else

        if @form_option.content.empty?
          @form_option.content = @form_option.content << params[:content]
        else
          @form_option.content = @form_option.content << "&" << params[:content]
        end
        if @form_option.save
          redirect_to :back, notice: "新增成功！"
        else
          redirect_to :back, alert: "新增失败！"
        end

    end
  end

  def delete_item
    form_option = FormOption.find(params[:id])
    new_record = form_option.content.split('&')
    new_record.delete(params[:item])
    form_option.content = new_record.join("&")
    if form_option.save
      redirect_to form_options_path, notice: "成功删除！"
    else
      redirect_to :back, alert: "删除失败！"
    end
  end

  private
  def form_option_params
    params.require(:form_option).permit(:field, :content)
  end
end

app/helpers/form_options_helper.rb
module FormOptionsHelper
end

app/views/form_options/index.html.erb
<div class="container">
  <div class="col-sm-4 col-sm-offset-4">
    <h3>新增表单选项</h3>
    <% if @form_option.errors.any? %>
    <ul>
      <% @form_option.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <% end %>
    <%= simple_form_for @form_option do |f| %>
      <%= f.input :field, input_html: { class: "form-control"}, label: "字段" %>
      <%= f.input :content, label: "内容"%>
      <%= f.submit "submit", class: "btn btn-block btn-lg btn-success" %>
    <% end %>

    <br>
  </div>
  <br>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>字段</th>
        <th>内容</th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
      <% @form_options.each do |f| %>
        <tr>
          <td><%= f.field %></td>
          <td>
            <% f.content.split('&').each do |item| %>
              <%= content_tag(:span, "【") %>
              <%= item %>
              <%= link_to(content_tag(:i,"", class: "fa fa-trash"), delete_item_form_option_path(f, :item => item), "data-confirm": "确定要删除吗？", method: :post, class: "btn btn-xs")%>
              <%= content_tag(:span, "】") %>
            <% end %>
          </td>
          <td>
            <%= form_tag form_option_path(f), method: :put do %>
                <input type="text" value="" name="content" />
              <%= submit_tag "增加", class: "btn btn-default btn-xs" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>