config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get "welcome" => "welcome#index"

  resources :abnormals do
    collection do
      get :download_excel
      post :import
      post :check_reason
      get :word_cloud
      get :excel_file_status
    end
    member do
      post :update_envelop
    end
  end
  resources :imports do
    member do
      get :download_csv
    end
  end
  resources :form_options do
    member do
      post :delete_item
    end
  end
end

app/models/abnormal.rb
class Abnormal < ApplicationRecord
  belongs_to :import,optional: true
  mount_uploader :image, ImageUploader
  # validates_presence_of :envelop, message: "制工袋不能为空！"
  # validates_length_of :envelop, message: "输入的制工袋位数有误，请输入6位数制工袋~", minimum: 6
  # validate :check_envelop, on: :create

  ENVELOP_RE = /\d{6}/

  # 根据时间筛选资料
  def self.render_filter_data(params)
    abnormals = Abnormal.where( "input_time >= ?", Date.parse(params[:start_on]).beginning_of_day ) if params[:start_on].present?
    abnormals = abnormals.where( "input_time <= ?", Date.parse(params[:end_on]).end_of_day ) if params[:end_on].present?
    abnormals = Abnormal.where( "input_time >= ?", Time.now.months_ago(2).at_beginning_of_month ) if !params[:start_on].present? && !params[:end_on].present?
    return abnormals.order(id: "desc")
  end

  # 返回生成部门统计哈希
  def self.render_department_hash(abnormals)
    department_hash = Hash.new(0)
      abnormals.each do |abnormal|
        if abnormal.department.present?
          abnormal.department.split("&").each do |d|
            department_hash[d] += abnormal.quantity
          end
        else
          department_hash["其他"] += abnormal.quantity
        end
      end
    return department_hash
  end

  # 返回生成按处理方式统计哈希
  def self.render_deal_method_hash(abnormals)
    deal_method_hash = Hash.new(0)
      abnormals.each do |abnormal|
        if abnormal.deal_method.present?
          abnormal.deal_method.split("&").each do |d|
            deal_method_hash[d] += abnormal.quantity
          end
        else
          deal_method_hash["其他"] += abnormal.quantity
        end
      end
    return deal_method_hash
  end

  #增加记录
  def self.create_abnormal(params, abnormal_params)
    abnormal = Abnormal.new(abnormal_params)
    abnormal.envelop = params[:abnormal][:envelop].gsub(/\s/, '')
    abnormal.model_no = params[:abnormal][:model_no].gsub(/\s/, '')
    abnormal.department = params[:abnormal][:department].map{|x| x.split(" ").join("&")}.join('&')
    abnormal.faulter = params[:abnormal][:faulter].split(' ').join('&')
    abnormal.deal_method = params[:abnormal][:deal_method].map{|x| x.split(" ").join("&")}.join('&')
    if abnormal.save
      if abnormal.envelop.present?
        GetEnvelopDetailJob.perform_later(abnormal.id)
      elsif @abnormal.model_no.present?
        GetModelNoDetailJob.perform_later(abnormal.id)
      end
      CheckFormFieldJob.perform_later(params[:abnormal][:principal], params[:abnormal][:department], params[:abnormal][:deal_method])
      return true
    else
      return false
    end
  end

  #更新记录
  def update_abnormal(params)
    self.envelop = params[:abnormal][:envelop].gsub(/\s/, '') if params[:abnormal][:envelop].present?
    self.model_no = params[:abnormal][:model_no].gsub(/\s/, '') if params[:abnormal][:model_no].present?
    self.department = params[:abnormal][:department].map{|x| x.split(" ").join("&")}.join('&') if params[:abnormal][:department].join.present?
    self.faulter = params[:abnormal][:faulter].split(' ').join('&') if params[:abnormal][:faultet].present?
    self.deal_method = params[:abnormal][:deal_method].map{|x| x.split(" ").join("&")}.join('&') if params[:abnormal][:deal_method].join.present?
    envelop = self.envelop
    if self.update(abnormal_params)
      if envelop != params[:abnormal][:envelop]
        if self.envelop.present?
          GetEnvelopDetailJob.perform_later(abnormal.id)
        elsif self.model_no.present?
          GetModelNoDetailJob.perform_later(abnormal.id)
        end
      end
      return true
    else
      return false
    end
  end

  private
  def check_envelop
    unless self.envelop =~ ENVELOP_RE
      self.errors.add :envelop, "请输入有效的6位数制工袋号码~"
      return false
    end
  end

end

app/controllers/abnormals_controller.rb
class AbnormalsController < ApplicationController
  before_action :find_abnormal, only: [:destroy, :edit, :update, :update_envelop]
  before_action :admin_required, only: [:new, :create, :edit, :update, :destroy, :import, :update_envelop]

  def  index
    @abnormals = Abnormal.render_filter_data(params)
    @start_date = params[:start_on].present? ?  Date.parse(params[:start_on]).beginning_of_day : Time.now.months_ago(2).at_beginning_of_month
    @end_date = Date.parse(params[:end_on]).end_of_day if params[:end_on].present?
    # 页面备用的链接
    @envelop_link = "http://www.diastarasia.com/Diastar/Envelop.do?action=searchEnvelop&envelopID="
    @model_no_link = "http://www.diastarasia.com/Diastar/ModelNo.do?action=searchModelNo&SearchBy=ByModelNo&modelNo="
    # 生成 按部门，按处理方式 分类的备用哈希
    @department_hash = Abnormal.render_department_hash(@abnormals)
    @deal_method_hash = Abnormal.render_deal_method_hash(@abnormals)
    respond_to do |format|
      format.xlsx{}
      format.html {
        # 生成图表所需要的哈希参数，然后在前端喂给js
        @all_department_chart_pie = render_chart_description(@department_hash, "department", "pie", "各部门异常数据")
        @all_department_chart_bar = render_chart_description(@department_hash, "department", "bar", "各部门异常数据")
        @all_deal_with_chart_pie = render_chart_description(@deal_method_hash, "deal_method", "pie", "各处理方式统计")
        @all_deal_with_chart_bar = render_chart_description(@deal_method_hash, "deal_method", "bar", "各处理方式统计")
        create_word_cloud_data(@start_date, @end_date, @department_hash, @deal_method_hash)
      }
    end
    @abnormals = @abnormals.paginate(:page => params[:page], :per_page => 30)
  end

  def new
    @abnormal = Abnormal.new
    @principal_option = option_1 = FormOption.where(:field => "负责人").first && option_1.content.split('&')
    @department_option = option_2 = FormOption.where(:field => "部门").first && option_2.content.split('&')
    @deal_method_option = option_3 = FormOption.where(:field => "处理方式").first && option_3.content.split('&')
  end

  def create
    if Abnormal.create_abnormal(params, abnormal_params)
      redirect_to :abnormals_path, notice: "新增成功！"
    else
      render :new
    end
  end

  def edit
    @principal_option = option_1= FormOption.where(:field => "负责人") && option_1.first.content.split('&')
    @department_option = option_2  = FormOption.where(:field => "部门") && option_2.first.content.split('&')
    @deal_method_option = option_3 = FormOption.where(:field => "处理方式") && option_3.first.content.split('&')
  end

  def update
    if @abnormal.update_abnormal(params)
      redirect_to :abnormals_path, notice: "更新成功!"
    else
      render :new
    end
  end

  # 发起下载
  def download_excel
    time = Time.now.in_time_zone(8).strftime("%m-%d %H:%M")
    GenerateExcelJob.perform_later(params[:start_on], params[:end_on], time, root_url)
    render :json => { :status => "success", :download_url => "#{root_url}office/#{time}.xlsx", :file_url => "#{Rails.root}/public/office/#{time}.xlsx"}
  end

  # 查询文件生成状态
  def excel_file_status
    if File.exist?(params[:file_url])
      render :json => {:status => "ok"}
    else
      render :json => {:status => "failed"}
    end
  end

  # 生成词云图
  def word_cloud
    @word_array = open("#{Rails.root}/public/wordarray/#{params[:file_name]}.txt","r"){|f|f.read}
    render :layout => false
  end

  def destroy
    if @abnormal.destroy
      redirect_to abnormals_path, alert: "已删除！"
    end
  end

  # 手动派出爬虫
  def update_envelop
    if @abnormal.envelop.present?
      GetEnvelopDetailJob.perform_later(@abnormal.id)
    elsif @abnormal.model_no.present?
      GetModelNoDetailJob.perform_later(@abnormal.id)
    end
    redirect_to :back, notice: "已提交更新~！"
  end

  # 导入csv文件
  def import
    redirect_to :back, notice: Import.import_abnormals(params)
  end

  private
  def abnormal_params
    params.require(:abnormal).permit(:envelop, :principal, :image, :reason, :faulter, :new_delivery, :department, :remarks, :input_time, :client, :model_no, :quantity, :raw_delivery, :merchandiser, :deal_method)
  end

  def find_abnormal
    @abnormal = Abnormal.find(params[:id])
  end

  def create_word_cloud_data(start_date, end_date, department_hash, deal_method_hash)
    # 为生成word_cloud准备数据
    @department_hash_file = {}
    @deal_method_hash_file = {}
    @all_reason_file = SecureRandom.hex 6
    GenerateWordArrayJob.perform_later("all", "all", start_date.to_s, (end_date.to_s if end_date.to_s.present?), @all_reason_file)
    department_hash.each do |k, v|
      file_name = SecureRandom.hex 6
      GenerateWordArrayJob.perform_later("department", k, start_date.to_s, (end_date.to_s if end_date.to_s.present?), file_name )
      @department_hash_file[k] =  file_name
    end
    deal_method_hash.each do |k, v|
      file_name = SecureRandom.hex 6
      GenerateWordArrayJob.perform_later("deal_method", k, start_date.to_s, (end_date.to_s if end_date.to_s.present?), file_name )
      @deal_method_hash_file[k] = file_name
    end
  end

  # 返回一个图表所需要的数据。
  def render_chart_description(option_hash, category, style, title)
    bc = []
    fc = []
    color_array = (0..255).to_a
    color_array.shuffle[1..option_hash.count].zip(color_array.shuffle, color_array.shuffle) do |a, b, c|
    bc << "rgba(#{a},#{b},#{c}, 0.2)"
      fc << "rgba(#{a},#{b},#{c}, 1)"
    end
      {
        type: style,
        data: {
            datasets: [{
                data: option_hash.values,
                backgroundColor: bc,
                borderColor: fc,
                borderWidth: 1,
                hoverBorderWidth: 2,
                dataLabels: {
                  colors: fc}
            }],
            labels: option_hash.keys},
        options: {
            responsive: true,
            legend: false,
            title: {
                display: false,
                text: title
            },
            animation: {
                animateScale: true,
                animateRotate: true
            },
            pieceLabel: {
            render: 'label',
            fontColor: '#666',
            position: 'outside'
          }
        }
      }
  end
end

app/helpers/abnormals_helper.rb
module AbnormalsHelper
  def render_content_display(content, style, *group_style)
    color = ["info", "warning", "danger", "primary", "default"]
    if content.present?
      result = []
      if content.include?("&")
        unless group_style.present?
          content.split("&").zip(color.shuffle) do |a, c|
            result << content_tag(:div, content_tag(:p, a, class: "label label-#{c}"), style: "margin: 0px;")
          end
          return result.join("<br>").html_safe
        else
          content.split("&").map!{|a| content_tag(:div, content_tag(:p, a, class: "label label-#{style}"))}.join("<br>").html_safe
        end
      else
        content_tag(:p, content, class: "label label-#{style}")
      end

    end
  end

  def render_last_three_month_start(date)
    date.months_ago(2).strftime("%Y-%m-1")
  end

  def render_last_three_month_end(date)
      date
  end

  def render_rand_color_btn(name,url, id, style)
    color = "#{rand(255)},#{rand(255)},#{rand(255)}"
      link_to name, url, id: id, class: "btn #{style} analyze-btn", style: "margin: 1px; background: rgba(#{color}, 0.3); color: #666; border-color:rgba(#{color},1);"
  end

  def render_date_helper(start_on, end_on)
    start_m = start_on.present? ? start_on.strftime("%Y-%m-%d") : "#{Date.today.month - 2}月1日"
    end_m = end_on.present? ? end_on.strftime("%Y-%m-%d") : "今天"
    return "#{start_m} ~ #{end_m}"
  end

  def render_month_first(m)
    Date.parse("#{Date.today.year}-#{m}-1").beginning_of_day
  end

  def render_month_last(m)
    Date.parse("#{Date.today.year}-#{m + 1}-1").yesterday.end_of_day
  end
end

app/views/abnormals/index.html.erb
<div style="position: relative;">
  <div class="col-sm-6">
    <%= form_tag abnormals_path, :method => :get do %>
        筛选资料：<%= text_field_tag :start_on, params[:start_on], :id => "start_date", :value => render_last_three_month_start(Date.today) %>
        ～
        <%= text_field_tag :end_on, params[:end_on], :id => "end_date", :value => render_last_three_month_end(Date.today) %>
        <%= submit_tag "送出筛选", :class => "btn btn-success btn-sm" %>
    <% end %>
    <% current_m = Date.today.month %>
    快速选择：
    <%= link_to "近3月", abnormals_path, class: "btn btn-xs btn-success" %>
    <%= link_to "#{current_m}月", abnormals_path(start_on: render_month_first(current_m), end_on: render_month_last(current_m)), class: "btn btn-xs btn-success" %>
    <%= link_to "#{current_m - 1}月", abnormals_path(start_on: render_month_first(current_m -1), end_on: render_month_last(current_m -1)), class: "btn btn-xs btn-success" %>
    <%= link_to "#{current_m - 2}月", abnormals_path(start_on: render_month_first(current_m -2), end_on: render_month_last(current_m -2)), class: "btn btn-xs btn-success" %>
  </div>
  <div class="col-sm-6 csv-form">
    <%= form_tag import_abnormals_path, multipart: true do %>
      <%= file_field_tag "csv_file" %>
      <%= text_field_tag "remarks", nil,  placeholder: '导入备注' %>
      <%= submit_tag "导入CSV数据", class: "btn btn-info btn-sm" %>
    <% end %>
    <%= link_to "新增记录", new_abnormal_path, class: "btn btn-sm btn-primary pull-left" %>
    <% if current_user && current_user.is_admin? %>
      <%= link_to "导出Excel",abnormals_path(:format => "xlsx"), id: "download_excel_btn", class: "btn btn-sm btn-success" %>
    <% else %>
      <button type="button" class="btn btn-success btn-sm" data-toggle="tooltip" data-placement="top" title="您不是管理员哦~">导出Excel</button>
    <% end %>
  </div>
  <br><br><br>
  <legend class="text-center" style="color: #555;">当前位置：<%= render_date_helper(@start_date, @end_date) %>的异常记录</legend>
  <!--======================== 生成图表 ========================-->
  <div class="row">
    <div class="col-md-6">
      <div class="row">
        <div class="col-sm-9">
          <h5 class="text-center" style="color: #666"><b>按部门统计件数</b></h5>
          <canvas id="myChart" width="160" height="140"></canvas>
        </div>
        <div class="col-sm-3">
            <% panel_color_a = ["primary", "success", "info", "warning", "danger"] %>
            <div class="panel panel-<%= panel_color_a.shuffle.first %>">
              <div class="panel-heading">
                <i class="fa fa-line-chart" aria-hidden="true"></i>
                 点击分析原因：
              </div>
              <div class="panel panel-body">
                <div class="row">
                  <% @department_hash_file.each do |k, v| %>
                    <div class="col-xs-6">
                      <%= render_rand_color_btn(k,"#", "reason_#{v}", "btn-xs") %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
        </div>
      </div>
      <canvas id="myChart_2" width="200" height="140"></canvas>
      </div>
      <div class="col-md-6">
        <div class="row">
          <div class="col-sm-9">
            <h5 class="text-center" style="color: #666"><b>按处理方式统计件数</b></h5>
            <canvas id="myChart_3" width="160" height="140"></canvas>
          </div>
          <div class="col-sm-3">
              <div class="panel panel-<%= panel_color_a.shuffle.first %>">
                <div class="panel-heading">
                  <i class="fa fa-line-chart" aria-hidden="true"></i>
                   点击分析原因：
                </div>
                <div class="panel panel-body">
                  <div class="row">
                    <% @deal_method_hash_file.each do |k, v| %>
                      <div class="col-xs-6">
                        <%= render_rand_color_btn(k,"#", "reason_#{v}", "btn-xs") %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
          </div>
        </div>
        <canvas id="myChart_4" width="200" height="140"></canvas>
        </div>
  </div>
  <!--======================== 图表结束 ========================-->

<!--======================== 查看原因 ========================-->

<%= link_to check_reason_abnormals_path, id: "all_reason_btn", class: "btn btn-success btn-lg btn-block"  do %>
  <i class="fa fa-lg fa-lightbulb-o" aria-hidden="true"></i>
  点击立即分析所有异常原因
<% end %>
<!--======================== 查看原因结束 ========================-->





<div class="container-fluid page">
<div class="row">


  <div class="pull-right">

  </div>
  <br>
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>日期</th>
        <th>客户</th>
        <th>制工袋</th>
        <th>款号</th>
        <th width="100px">图片</th>
        <th>版交期/出货期</th>
        <th>件数</th>
        <th>业务</th>
        <th>负责人</th>
        <th>异常原因</th>
        <th>当事人</th>
        <th>部门</th>
        <th>处理方式</th>
        <th>新交期</th>
        <th>备注</th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
      <% @abnormals.each do |abnormal| %>
        <tr>
          <td>
            <% if abnormal.input_time.present? %>
              <%= render_content_display abnormal.input_time.strftime("%y-%m-%d"), "success"%>
            <% end %>
          </td>
          <td><%= abnormal.client %></td>
          <td>
            <% if abnormal.envelop.present? %>
              <%= link_to abnormal.envelop, @envelop_link + abnormal.envelop, :target => "_blank" %>
            <% end %>
          </td>
          <td>
            <% if abnormal.model_no.present? %>
              <%= link_to abnormal.model_no, @model_no_link + abnormal.model_no, :target => "_blank" %>
            <% end %>
          </td>
          <td width="100px">
            <% if abnormal.image.present? %>
              <%= image_tag abnormal.image.thumb, style: "width: 100px;", class: "thumbnail img-responsive" %>
            <% else %>
              <%= image_tag("http://olmrxx9ks.bkt.clouddn.com/2017-08-19-%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202017-08-19%20%E4%B8%8B%E5%8D%885.51.10.png", style: "width: 100px;", class:"thumbnail img-responsive" )%>
            <% end %>
          </td>
          <td><%= render_content_display abnormal.raw_delivery, "success", "success" %></td>
          <td><%= abnormal.quantity %></td>
          <td><%= abnormal.merchandiser %></td>
          <td><%= abnormal.principal %></td>
          <td><%= abnormal.reason %></td>
          <td><%= render_content_display abnormal.faulter, "default", "default" %></td>
          <td><%= render_content_display abnormal.department, "info", "info" %></td>
          <td><%= render_content_display abnormal.deal_method, "danger", "danger" %></td>
          <td><%= render_content_display abnormal.new_delivery.to_s.sub(/\A20/, ''), "success", "success" %></td>
          <td><%= abnormal.remarks %></td>
          <td>
            <%= link_to "编辑", edit_abnormal_path(abnormal), class: "btn btn-info btn-xs" %>
            <%= link_to "删除", abnormal_path(abnormal), method: :delete, "data-confirm": "确定要删除吗？", class: "btn btn-danger btn-xs" %>
            <%= link_to "Get", update_envelop_abnormal_path(abnormal), method: :post, class: "btn btn-default btn-xs" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

      <div class="text-center">
        <%= will_paginate @posts %>
      </div>


</div>
</div>
</div>

<!--======================== 以下是overlay ========================-->
<div id="overlay"  onclick="off()">
  <div id="text_1" style= "display: none;" class="text-center">
  <i  class="fa fa-spinner fa-spin fa-fw"></i>
  正在生成数据，请稍等~
  </div>
  <div id="text_2" style="display: none;" class="text-center">
    已生成数据，尽快下载哦~
    <br>
    <%= link_to "立即下载", "/", class: "btn btn-info btn-bg", id: "download_file_btn" %>
  </div>
<!--=========== 以下是显示word cloud ===========-->
  <div id="word_cloud_container" style="display: none; overflow-x: auto; overflow-y: auto; height: 98%; width:98%; margin: auto; margin-top: 1%"></div>
<!--=========== 显示word cloud结束 ===========-->
</div>
<!--======================== 以上是overlay ========================-->

<!--======================== 时间戳辅助 ========================-->
<%= hidden_field_tag :start_on, params[:start_date_input], :value => @start_date.to_s %>
<%= hidden_field_tag :end_on, params[:end_date_input], :value => @end_date.present? ? @end_date.to_s : Time.now.to_s%>
<!--======================== 时间辅助结束 ========================-->



<!--======================== html结束 ========================-->



<!--======================== 以下是JS ========================-->
  <script type="text/javascript">

  var ctx = document.getElementById("myChart");
  var myChart = new Chart(ctx,<%= raw @all_department_chart_pie.to_json %>);
  var ctx = document.getElementById("myChart_2");
  var myChart_2 = new Chart(ctx,<%= raw @all_department_chart_bar.to_json %>);

  var ctx = document.getElementById("myChart_3");
  var myChart_3 = new Chart(ctx,<%= raw @all_deal_with_chart_pie.to_json %>);
  var ctx = document.getElementById("myChart_4");
  var myChart_4 = new Chart(ctx,<%= raw @all_deal_with_chart_bar.to_json %>);


  $("#download_excel_btn").click(function(evt){
    evt.preventDefault();
    var url = "<%= download_excel_abnormals_url %>"
    var start_on = $("#start_on").val();
    var end_on = $("#end_on").val();
    // 送出 Ajax
    $.ajax({
      url: url,
      method: 'get',
       dataType: 'json',
       data: { start_on: start_on, end_on: end_on },
       beforeSend: function(){
         $("#word_cloud_container").css("display", "none");
         $("#overlay").css("height", "100%");
         $("#text_1").css("display", "block");
         $("#text_2").css("display", "none");
       },
       success: function(data){
         if (data["status"] == "success"){
           $("#download_file_btn").prop("href", data["download_url"]);
           get_excel_file_status(data["file_url"]);
         }
       }
    })
  })

  function get_excel_file_status(file_url){
    var int = setInterval(function(){
    $.ajax({
      url: "/abnormals/excel_file_status",
      method: "get",
      dataType: "json",
      data: {file_url: file_url},
      success: function(data){
        if (data["status"] == "ok") {
          $("#text_1").css("display", "none");
          $("#text_2").css("display", "block");
          alert("已生成~");
          clearInterval(int);
        }
      }
    })
  }, 2000)
  }



  $("#download_file_btn").click(function(){
    $("#overlay").css("height", "0");
    $("#text_2").css("display", "none");
  })

  // 日期输入框的js辅助
  $("#start_date").datepicker({ format: "yyyy-mm-dd", language: "<%= I18n.locale %>" });
  $("#end_date").datepicker({ format: "yyyy-mm-dd", language: "<%= I18n.locale %>" });






  //异步加载word cloud
  function get_word_cloud(url){
    $.ajax({
      url: url,
      type:'get',
      dataType:'html',
      beforeSend: function(){
        $("#word_cloud_container").css("display", "none");
        $("#overlay").css("height", "100%");
        $("#text_1").css("display", "block");
      },
      success:function(data){
        $("#text_1").fadeOut();
        $("#text_2").fadeOut();
        $("#word_cloud_container").html(data);
        $("#word_cloud_container").fadeIn();
      }
    });
  }



  <% @deal_method_hash_file.each do |k, v| %>
    $("#reason_<%= v %>").click(function(){
        get_word_cloud('/abnormals/word_cloud' + "?file_name=" + "<%= v %>");
     return false;
    });
  <% end %>


  <% @department_hash_file.each do |k, v| %>
    $("#reason_<%= v %>").click(function(){
      get_word_cloud('/abnormals/word_cloud' + "?file_name=" + "<%= v %>");
    return false;
    });
  <% end %>

  $("#all_reason_btn").click(function(){
    get_word_cloud('/abnormals/word_cloud' + "?file_name=" + "<%= @all_reason_file %>");
    return false;
  })

  $(document).ready(function(){
    $.ajax({
      url: "/abnormals/word_cloud" + "?file_name=" + "<%= @department_hash_file.values.last %>",
      type:'get',
      dataType:'html',
      success:function(data){
        $("#word_cloud_container").html(data);
      }
    });
  })

  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })




</script>