config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get "welcome" => "welcome#index"

  resources :abnormals do
    collection do
      get :download_excel
      post :import
      post :check_reason
      get :word_cloud
      get :excel_file_status
    end
    member do
      post :update_envelop
    end
  end
  resources :imports do
    member do
      get :download_csv
    end
  end
  resources :form_options do
    member do
      post :delete_item
    end
  end
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 New Hope EA
        <br>Design by activeliang.

    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">New Hope EA</a>

        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li><%= link_to "首页", "/" %></li>
            </ul>
            <ul class="nav navbar-nav">
              <li><%= link_to "异常记录", abnormals_path %></li>
            </ul>
            <ul class="nav navbar-nav">
              <li><%= link_to "新增异常", new_abnormal_path %></li>
            </ul>
            <ul class="nav navbar-nav">
              <li><%= link_to "表单助手", form_options_path %></li>
            </ul>
            <ul class="nav navbar-nav">
              <li><%= link_to "导入记录", imports_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if !current_user %>
                <li><%= link_to("注册", new_user_registration_path) %> </li>
                <li><%= link_to(content_tag(:i, '登入', class: 'fa fa-sign-in'), new_user_session_path) %></li>
              <% else %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Hi!, <%= current_user.email %>
                      <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li> <%= link_to(content_tag(:i, '登出', class: 'fa fa-sign-out'), destroy_user_session_path, method: :delete) %> </li>
                  </ul>
                </li>
              <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>